# Generated by Django 5.0.4 on 2024-04-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogpost_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='datetime',
        ),
    ]
